# Generated by Django 3.2.19 on 2023-06-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230627_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='имя'),
        ),
    ]
