# Generated by Django 3.2.19 on 2023-07-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_subcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.PositiveIntegerField(default=0, verbose_name='количество свободного товара'),
        ),
    ]
